theme: minima
title: RunAsh 
author: RunAsh Digital Innovation Technologies Pivate Limited
email: admin@runash.in
description: > # RunAsh is an live streaming hybrid platform and marketplace for retailing

  


# social links
twitter_username: runashstartup # DO NOT include the @ character, or else the build will fail!
github_username:  runash # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
