














theme: minima
title: RunAsh 
author: admin@runash.in
#email: admin@runash.in
 
description: A live streaming marketplace for retailing "runash.in:"
               
          
 
#baseurl: runash.in
#url: runash.in









  


  


# social links
#twitter_username: runashstartup # DO NOT include the @ character, or else the build will fail!
github_username:  RunAsh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true #set to false to remove excerpts on the homepage 












