














theme: minima
title: RunAsh 
author: Founder Ram Murmu
email: admin@runash.in
description: A live streaming hybrid marketplace for retailing "runash.in:"
               
          
 
baseurl: runash.in
url: runash.in

 
  


  


# social links
#twitter_username: runashstartup # DO NOT include the @ character, or else the build will fail!
github_username:  runash # DO NOT include the @ character, or else the build will fail!

#Build setting
markdown: kramdown 
plugins: 
-jekylly-feed 
defaults:
-scope:
path: "project" 
type: "page"
path: "assets/img"
values:
image: true 

show_excerpts: true # set to false to remove excerpts on the homepage
